#!/usr/bin/env python

import sys
import requests
import os
import openai

# Get the query string from the command line argument
query_string = sys.argv[1]
stdin_string = sys.stdin.read()

template = "perform operation '{}' on the following input:\n{}".format(
    query_string, stdin_string)

openai.api_key = os.getenv("OPENAI_API_KEY")
response = openai.Completion.create(model="text-davinci-003",
                                    prompt=template,
                                    temperature=0,
                                    max_tokens=2000)

print(format(response.choices[0].text.strip()))
